version: "3.0"

services:
  redis:
    container_name: "cache-redis"
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
#    volumes:
#      - 'redis_data:/bitnami/redis/data'

  memcache:
    container_name: "cache-memcache"
    image: memcached
    ports:
      - "11211:11211"
  ssdb:
    container_name: "beego-ssdb"
    image: wendal/ssdb
    ports:
      - "8888:8888"